services:
  app:
    build: ./app
    expose: ["3000"]

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
      - ./docs:/usr/share/nginx/html/docs
    depends_on: [app]
