services:
#Объявление контейнер
  web:
  #Образ, который будет использоваться
    image: nginx:alpine
    #Имя контейнера
    container_name: con_1
    # Проброс портов: порт 80 хоста → порт 80 контейнера
    ports:
      - "80:80"    # HTTP редирект
      - "443:443"  # 🔒 HTTPS
    #В какую часть памяти будет произведен маппинг проекта
    volumes:
       - ./custom:/usr/share/nginx/html
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - nodeapp  # ✅ Ждем запуска nodeapp
    networks:
      - app-network  # ✅ Общая сеть

#Объявление контейнер
  nodeapp:
    #Указывает Docker собрать образ из DockerFile по пути /Server
    build: ./Server
    #Имя контейнера
    container_name: nodeapp

    ports:
    - "3000:3000"
    #В какую часть памяти будет произведен маппинг проекта
    volumes:
    - ./server:/app
    - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - app-network  # ✅ Общая сеть

networks:
  app-network:
    driver: bridge
    